name: Build package

on:
    workflow_call:
    push:

jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
              python-version: "3.10"
        - name: Install pypa/build
          run: >-
              python -m
              pip install
              build
              pyinstaller
              --user
        - name: Build pypi and exe bundles
          run: powershell.exe bin\release.ps1
        - uses: actions/upload-artifact@master
          with:
              name: dist-exe
              path: dist.exe\
        - uses: actions/upload-artifact@master
          with:
              name: dist-pypi
              path: dist\
